const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const ProduitBabalisteSchema = new Schema(
  {
    titre: { type: String, required: true, min: 3 },
    categorie: {
      type: String,
      required: true,
      enum: [
        "multimedia",
        "vehicule",
        "homme",
        "femme",
        "maison",
        "beaute",
        "enfant",
        "loisirs",
        "autres",
      ],
    },
    sous_categorie: {
      type: String,
      required: true,
      enum: [
        "tout",
        "telephone",
        "tablette",
        "ordinateur",
        "television",
        "son, photo & image",
        "jeux video",
        "accessoire et gadget",
        "reseau",
        "autres",

        "tout",
        "voiture",
        "moto",
        "velo",
        "bateau",
        "accessoire pour vehicule",

        "tout",
        "haut",
        "pontalon",
        "costume",
        "chaussure",
        "sac",
        "manteau",
        "sous vetement",
        "accessoire",
        "autre",

        "tout",
        "haut",
        "pontalon",
        "jupe et robe",
        "chaussure",
        "sac",
        "manteau",
        "accessoire",
        "sous vetement",
        "autre",

        "tout",
        "chanbre a coucher",
        "salon",
        "cuisine",
        "salle de bain",
        "espace exterieur",
        "bagagerie",
        "animalerie",
        "bricolage",

        "tout",
        "maquillage",
        "parfum",
        "cheveux",
        "corps et douche",
        "peau",
        "autre",
        "accessoire",

        "tout",
        "equipement bebe",
        "vetement garcon",
        "vetement fille",
        "jouet",
        "autre",
        "accessoire",

        "tout",
        "sport",
        "livre DVD magasine",
        "instrument de musique",
        "billet et ticket",
        "autre",

        "tout",
        "materiel profissionnel",
        "autre",
      ],
    },
    images: [{ type: Schema.Types.ObjectId, ref: "Images_Produit_babaliste" }],
    prix: { type: Number, required: true, min: 3 },
    nomVendeur: { type: String, required: true, min: 3 },
    typeVendeur: { type: String, enum: ["normal", "Pro"] },
    numeroVendeur: { type: String, required: true, min: 3 },
    emailVendeur: { type: String, required: true, min: 3 },
    nbMessages: { type: Number, required: true, min: 3 },
    nbVues: { type: Number, required: true, min: 3 },
    User: { type: Schema.Types.ObjectId, ref: "User" },
  },
  { timestamps: true }
);
const User = mongoose.model("Produit_babaliste", ProduitBabalisteSchema);
module.exports = User;
